Fix rename error when sid is empty
**before:**
```
    # docker run -tid --name 111 ubuntu top
    # docker run -tid --name 222 --net container:111 ubuntu top
    # docker rename 222 333
    Error response from daemon: invalid id:
    Error: failed to rename container named 222
```

**after:**
```
    # docker run -tid --name 111 ubuntu top
    # docker run -tid --name 222 --net container:111 ubuntu top
    # docker rename 222 333
    # docker ps
    CONTAINER ID        IMAGE               COMMAND             CREATED
    STATUS              PORTS               NAMES
    942d504e5170        ubuntu              "top"               7 seconds
    ago       Up 6 seconds                            333
    06d00188bf90        ubuntu              "top"               12 seconds
    ago      Up 11 seconds                           111
```

backport from https://github.com/moby/moby/pull/30090 without conflicts.
fix DTS2017070307844

Signed-off-by: Wang Xing <hzwangxing@corp.netease.com>
Signed-off-by: Yuanhong Peng <pengyuanhong@huawei.com>